#!/bin/bash

TOP=~ocs/matlab/LAST/LAST_WebApi
LOGDIR=/var/log/ocs/api/server

mkdir -p ${LOGDIR}
last-matlab -nodisplay -batch "addpath('"${TOP}"'); addpath('"${TOP}/Simple3rdParty"'); addpath('"${TOP}/+Simple"'); run('obs.SnisOCS.m')" >>${LOGDIR}/$(date --iso).log 2>&1
